apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project
resources:
  - namespace.yaml
  - ../../todo-app/manifests
  - ../../todo-backend/manifests
  - ../../broadcaster/manifests
images:
  - name: parthvasave/todo-app
    newTag: "3.5"
  - name: parthvasave/todo-backend
    newTag: "3.5"
  - name: parthvasave/broadcaster
    newTag: "4.6"
