apiVersion: v1
kind: Secret
metadata:
    name: broadcaster-secret
    namespace: project
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:vvEABPaOWsFoeZNFdo4cfNfHTDUZOK3RznLxBB0lTQmt8Ko03rIj4IuhLl01eOOsPHiM11K/QFGCxUsBnJwvdd6gDv0JaatrzrjO+YYaBG5FEzBmT0ppq0zPRcM0a5SWr5wlmXHPxdg2VxPWNPy9+HIFvGrtjxHwhw==,iv:UtCB++FowPe1QsZU3fWTgFtKWwfbAN20snvqrFIVpWk=,tag:rY4WERdqzlESaSuHS453rg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6REVlR2dIbjJjQTl0S1Z3
            WW1tZGo1V0Q4VVgzcU0vY2tkMm5GRnMrTnpJClB5OHdLVUx6d0g0ZmhYNTMrU2N6
            UUM1NXZjWGpXRWk4ZGFVc3RxSzBocTQKLS0tIFZxWndiRk1qRElBR2wxOWMwelBi
            dGk4TEc1aWsyYTMrM3lnWlByZjAvMTAKD3cQVcwVDJIw2uMUnqKbTITnBWADqQTd
            4WrLRgVgo+yTvGmmKW4br9xb+5Ee7f8XZkzuLVy6AHUUiadf49/wLg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15fad92qkqrfwuwrp6j68z9jeteg9ht9r0zlqk8fzw4yq6lwee3zshrcvgf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-14T14:55:22Z"
    mac: ENC[AES256_GCM,data:1MIMY+hQ5irXaMsDXsCYNb2HB4dd8sP/a7JibuTPFrU4XNC+RvITB02/XIkW6qmk6F6GdywvQ7OcKbRYBKI8CNgjwkX7GtUj2O70zpOfjiV5lBTvjsZDto8DWLq8byX9yZuvZ8fWGKW7iblt/YLYUhTqEL59F9kyANlivcvctAw=,iv:LyfKzlh2a+5zPhl2nsfhY8zq7zhqHpL1LkmIHucV4Xw=,tag:D28xGG08heal/7CZzPySVQ==,type:str]
    version: 3.13.3
