apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: todo-app-healthcheck
  namespace: project
spec:
  default:
    config:
      type: HTTP
      httpHealthCheck:
        port: 3000
        requestPath: /healthz
  targetRef:
    group: ""
    kind: Service
    name: todo-app
