apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: project
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:ZOtrWA==,iv:xosSjFmgRElJNoWnh3HNXB8TCpJKZcvdjJ09ZrUYXd4=,tag:5Rj+7wE4VrkAMP+ctRl2Mw==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:+GUORw==,iv:7kceCLPd6QCg/zNCdwVDipHTvAblOra/T7HHPd0hvnY=,tag:KwvFCCAoBlLd6Ihr/AbRWA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:XH1lUQlumCJ6D64N7BhQZHLvLCiyuhJF0ti46IEfqiA=,iv:kWp11bufvdzZpDkEFErMdX4de60bYU8kT9PReNuajic=,tag:jR9yhok/GHHjE8Z0iO6MrQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCSm5QclVBSVNaemFHWmhE
            dWJhNWpYbzZSZGlQSjNUcDl4bmVnTEhhR2hRCjJtOURBN1hucDhqOHI0M1dHY1ho
            UDZLNXRNQ0NKbFowajZDYTZJTGhNa3cKLS0tIHdyV1RRMnZIdFFXZS8wZFBRR0dR
            U1F5YW9CVFcrSHlYOXljNlpNRDN1NFEK1B+xaA8bKAAfsktP6qLK5ZmwC+x2u5h6
            tjWrwBcNXUEfD2A/InfnwbTPJ/57ItJJIoOvOMIBI0O74dBfAkRy5g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15fad92qkqrfwuwrp6j68z9jeteg9ht9r0zlqk8fzw4yq6lwee3zshrcvgf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-14T08:58:41Z"
    mac: ENC[AES256_GCM,data:x1pDnaG7C0q4SyrwvfyhlMvgErYdNzsuchnd6mF3uLlG6ZX273RnsjGz+UjaS8SO78yjWRqEafPw7JB7k8OZ2lsA9/WVlV9R7pm/jvVaGSx+SdW4OuwS/IRHE8cbgRVIDYiAX0NbaOgJBRd2gGw0WefXMQKPgXPYXxtP8tHNcL0=,iv:ciM4WDMS0IUOkwsJp81WM+kgrqNTT2VIa1wq3VCVDAs=,tag:P7Q8H/AEVsGAX4hh5BEVfg==,type:str]
    version: 3.13.3
